import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const projectRoot = path.resolve(__dirname, '..');
const readmePath = path.join(projectRoot, 'README.md');
const docsHomePath = path.join(projectRoot, 'docs/pages/index.md');

try {
  let content = fs.readFileSync(readmePath, 'utf8');

  // Add warning header
  const header = `<!-- 
  DO NOT EDIT THIS FILE DIRECTLY.
  This file is generated automatically from README.md during the build process.
  Edit README.md instead.
-->\n\n`;

  // Replace absolute GitHub Pages URLs with relative paths for the docs site
  // This allows the README to point to the live site, while the docs site uses internal navigation
  const productionUrl = 'https://jurra.github.io/qucat-circuit-generator/';
  content = content.replace(new RegExp(productionUrl, 'g'), '');

  fs.writeFileSync(docsHomePath, header + content);
  console.log('✓ Successfully synced README.md to docs/pages/index.md');
} catch (error) {
  console.error('Error syncing README:', error);
  process.exit(1);
}
